production:
  coastsun.ru: "AKaGj00BAAAAz2OPKAIA608dLocZlaNxLvYZYsVUM57Ip9MAAAAAAAAAAAAN3VjKAA2y2tQtrqARB1EU80UO3w=="
  www.coastsun.ru: "AKaGj00BAAAAz2OPKAIA608dLocZlaNxLvYZYsVUM57Ip9MAAAAAAAAAAAAN3VjKAA2y2tQtrqARB1EU80UO3w=="
  localhost: "AKaGj00BAAAAz2OPKAIA608dLocZlaNxLvYZYsVUM57Ip9MAAAAAAAAAAAAN3VjKAA2y2tQtrqARB1EU80UO3w=="
 
  # If you have a single domain just, paste API Key. No YML key required.
development:
  "AKaGj00BAAAAz2OPKAIA608dLocZlaNxLvYZYsVUM57Ip9MAAAAAAAAAAAAN3VjKAA2y2tQtrqARB1EU80UO3w=="
test:
  test # Leave test ENV as it is for specs to pass
